spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/jyparking?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
    username: root
    password: root
    initialSize: 0
    maxActive: 20
    maxIdle: 20
    minIdle: 1
    maxWait: 60000
    type: com.alibaba.druid.pool.DruidDataSource